name: Optin
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - datasets==2.19.2
      - dill==0.3.8
      - evaluate==0.4.2
      - filelock==3.14.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - huggingface-hub==0.23.3
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - timm==1.0.3
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.4
      - transformers==4.41.2
      - triton==3.0.0
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: ./miniconda3/envs/Optin
